# Generated by Django 4.2.4 on 2023-08-17 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rollNo', models.CharField(max_length=9, unique=True)),
                ('type', models.CharField(choices=[('UG', 'UG'), ('PG', 'PG'), ('RS', 'RS')], max_length=4)),
                ('batch', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('hall', models.CharField(max_length=4)),
                ('profilePic', models.ImageField(blank=True, upload_to='profile_pics')),
            ],
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollNo', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('slot', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snacks', 'Snacks'), ('dinner', 'Dinner')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.user')),
            ],
            options={
                'unique_together': {('user', 'date', 'slot')},
            },
        ),
    ]
