# Generated by Django 4.2.4 on 2023-08-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='rollNo',
            field=models.CharField(max_length=9),
        ),
    ]
