# Generated by Django 4.2.4 on 2023-08-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_alter_checkin_rollno'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foodChoice',
            field=models.CharField(choices=[('veg', 'Veg'), ('nonveg', 'Non-Veg')], default='veg', max_length=10),
        ),
    ]
